### ISSUE TITLE
大佬 idea导入成功 但是无法编译（内有情况图）

### ISSUE THREAD

**Issue by LilithXing** [mxdldev/spring-cloud-flycloud#3]
## 项目已经成功导入

![001](https://user-images.githubusercontent.com/20179864/56375120-4745f080-6237-11e9-8b9e-2037d0600e4f.png)
SpringCloud 依赖也导入了
![002](https://user-images.githubusercontent.com/20179864/56375139-5331b280-6237-11e9-8866-928cb5362a58.png)
---------
## 但是编译开发的时候 直接找不到包 

![003](https://user-images.githubusercontent.com/20179864/56375192-72304480-6237-11e9-863c-83b43d20dd5e.png)

## 看了下gradle面板 依赖已经成功导入了啊

![004](https://user-images.githubusercontent.com/20179864/56375309-b6bbe000-6237-11e9-9b80-5c3b98690b48.png)

--------

**Comment by mxdldev** [comment]
> ## 项目已经成功导入
> ## ![001](https://user-images.githubusercontent.com/20179864/56375120-4745f080-6237-11e9-8b9e-2037d0600e4f.png)
> SpringCloud 依赖也导入了
> ![002](https://user-images.githubusercontent.com/20179864/56375139-5331b280-6237-11e9-8866-928cb5362a58.png)
> ## 但是编译开发的时候 直接找不到包
> ![003](https://user-images.githubusercontent.com/20179864/56375192-72304480-6237-11e9-863c-83b43d20dd5e.png)
> 
> ## 所有模块都找不到依赖包
> ## 看了下gradle面板 依赖已经成功导入了啊
> ![004](https://user-images.githubusercontent.com/20179864/56375309-b6bbe000-6237-11e9-9b80-5c3b98690b48.png)
> 
> ## 这该怎么解决呢？

你是不是没有下载项目构建工具gradle？下载完毕需要在IDEA里面进行配置
![gradle](https://user-images.githubusercontent.com/7042195/56399868-2f945980-6283-11e9-8473-81295e4ffccf.png)

**Comment by LilithXing** [comment]
已经解决了
手动执行了build --refresh-dependencies
又好了

魔幻
